name: Build latest (Ubuntu Linux x32)

on: [push, pull_request]

jobs:
  build_on_ubuntu:
    name: Build ${{ matrix.config.plat }} (${{ matrix.config.bits }} bit) on Ubuntu
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { plat: "Linux", bits: 32 }
    steps:
      - uses: actions/checkout@v2

      - name: Install Shared Dependencies
        run: |
          sudo apt-get -y update &&
          sudo apt-get -y install build-essential

      - name: Install Dependencies for ${{ matrix.config.plat }} (${{ matrix.config.bits }} bit)
        if: matrix.config.plat == 'Linux' && matrix.config.bits == 32
        run: |
          sudo dpkg --add-architecture i386 \
            && sudo apt-get -y update \
            && sudo apt-get -y install gcc-multilib libx11-dev:i386 libxi-dev:i386 libgl1-mesa-dev:i386

      # Build
      - name: Build for ${{ matrix.config.plat }} (${{ matrix.config.bits }} bit)
        if: matrix.config.plat == 'Linux' && matrix.config.bits == 32
        run: |
          # Note, this overwrites the previous flags
          make linux CFLAGS="-m32" LDFLAGS="-m32"

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube'
          DEST_NAME: 'ClassiCube'