name: Build latest (Windows x64)

on: [push, pull_request]

jobs:
  build_on_windows:
    name: Build ${{ matrix.config.plat }} (${{ matrix.config.bits }} bit) on Windows
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { plat: "Windows", bits: 64 }

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      # Build
      - name: Build for ${{ matrix.config.plat }} (${{ matrix.config.bits }} bit)
        if: matrix.config.plat == 'Windows' && matrix.config.bits == 64
        run: |
          msbuild src\ClassiCube.vcxproj `
            -property:Configuration=Debug -property:Platform=x64 `
            -property:WindowsTargetPlatformVersion=10 -property:PlatformToolset=v142

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'src\x64\Debug\ClassiCube.exe'
          DEST_NAME: 'ClassiCube.exe'
