name: Build latest (MacOS x64)

on: [push, pull_request]

jobs:
  build_on_mac:
    name: Build ${{ matrix.config.plat }} (${{ matrix.config.bits }} bit) on Mac
    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { plat: "Mac", bits: 64 }

    steps:
      - uses: actions/checkout@v2

      # Build
      - name: Build for ${{ matrix.config.plat }} (${{ matrix.config.bits }} bit)
        if: matrix.config.plat == 'Mac' && matrix.config.bits == 64
        run: |
          make mac_x64

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'src\ClassiCube.app'
          DEST_NAME: 'ClassiCube.app'
