name: Build latest (Ubuntu Linux x64)

on: [push, pull_request]

jobs:
  build_on_ubuntu:
    name: Build ${{ matrix.config.plat }} (${{ matrix.config.bits }} bit) on Ubuntu
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { plat: "Linux", bits: 64 }

    steps:
      - uses: actions/checkout@v2

      - name: Install Shared Dependencies
        run: |
          sudo apt-get -y update &&
          sudo apt-get -y install build-essential

      # Install platform specific dependencies
      - name: Install Dependencies for ${{ matrix.config.plat }} (${{ matrix.config.bits }} bit)
        if: matrix.config.plat == 'Linux' && matrix.config.bits == 64
        run: |
          sudo apt-get -y install libx11-dev libxi-dev libgl1-mesa-dev

      # Build
      - name: Build for ${{ matrix.config.plat }} (${{ matrix.config.bits }} bit)
        if: matrix.config.plat == 'Linux' && matrix.config.bits == 64
        run: |
          make linux

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube.tar.gz'
          DEST_NAME: 'ClassiCube.tar.gz'